before:
  hooks:
    - go mod tidy
builds:
  - id: kubeconfig-updater
    main: main.go
    binary: kubeconfig-updater-backend
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X 'github.krafton.com/xtrm/kubeconfig-updater/cmd.Version=v{{.Version}}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
