build-proto:
	protoc --go_out=../backend/controller/kubeconfig_service/ --go_opt=paths=source_relative --go-grpc_out=../backend/controller/kubeconfig_service/ --go-grpc_opt=paths=source_relative protos/*
