// source: protos/kubeconfig_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var protos_common_pb = require('../protos/common_pb.js');
goog.object.extend(proto, protos_common_pb);
goog.exportSymbol('proto.kubeconfig.AggregatedClusterMetadata', null, global);
goog.exportSymbol('proto.kubeconfig.ClusterInformationStatus', null, global);
goog.exportSymbol('proto.kubeconfig.ClusterMetadata', null, global);
goog.exportSymbol('proto.kubeconfig.CredResolverConfig', null, global);
goog.exportSymbol('proto.kubeconfig.CredResolversReq', null, global);
goog.exportSymbol('proto.kubeconfig.CredentialResolverKind', null, global);
goog.exportSymbol('proto.kubeconfig.CredentialResolverStatus', null, global);
goog.exportSymbol('proto.kubeconfig.DeleteCredResolverReq', null, global);
goog.exportSymbol('proto.kubeconfig.GetAvailableClustersRes', null, global);
goog.exportSymbol('proto.kubeconfig.GetCredResolversRes', null, global);
goog.exportSymbol('proto.kubeconfig.KubeConfigReq', null, global);
goog.exportSymbol('proto.kubeconfig.KubeConfigRes', null, global);
goog.exportSymbol('proto.kubeconfig.MetadataResolverType', null, global);
goog.exportSymbol('proto.kubeconfig.RegisterClusterReq', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kubeconfig.CredResolverConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kubeconfig.CredResolverConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kubeconfig.CredResolverConfig.displayName = 'proto.kubeconfig.CredResolverConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kubeconfig.CredResolversReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.kubeconfig.CredResolversReq.repeatedFields_, null);
};
goog.inherits(proto.kubeconfig.CredResolversReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kubeconfig.CredResolversReq.displayName = 'proto.kubeconfig.CredResolversReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kubeconfig.GetCredResolversRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.kubeconfig.GetCredResolversRes.repeatedFields_, null);
};
goog.inherits(proto.kubeconfig.GetCredResolversRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kubeconfig.GetCredResolversRes.displayName = 'proto.kubeconfig.GetCredResolversRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kubeconfig.DeleteCredResolverReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kubeconfig.DeleteCredResolverReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kubeconfig.DeleteCredResolverReq.displayName = 'proto.kubeconfig.DeleteCredResolverReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kubeconfig.KubeConfigReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kubeconfig.KubeConfigReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kubeconfig.KubeConfigReq.displayName = 'proto.kubeconfig.KubeConfigReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kubeconfig.KubeConfigRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kubeconfig.KubeConfigRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kubeconfig.KubeConfigRes.displayName = 'proto.kubeconfig.KubeConfigRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kubeconfig.ClusterMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kubeconfig.ClusterMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kubeconfig.ClusterMetadata.displayName = 'proto.kubeconfig.ClusterMetadata';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kubeconfig.AggregatedClusterMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.kubeconfig.AggregatedClusterMetadata.repeatedFields_, null);
};
goog.inherits(proto.kubeconfig.AggregatedClusterMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kubeconfig.AggregatedClusterMetadata.displayName = 'proto.kubeconfig.AggregatedClusterMetadata';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kubeconfig.GetAvailableClustersRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.kubeconfig.GetAvailableClustersRes.repeatedFields_, null);
};
goog.inherits(proto.kubeconfig.GetAvailableClustersRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kubeconfig.GetAvailableClustersRes.displayName = 'proto.kubeconfig.GetAvailableClustersRes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.kubeconfig.RegisterClusterReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.kubeconfig.RegisterClusterReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.kubeconfig.RegisterClusterReq.displayName = 'proto.kubeconfig.RegisterClusterReq';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kubeconfig.CredResolverConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.kubeconfig.CredResolverConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kubeconfig.CredResolverConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.CredResolverConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    accountid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    infravendor: jspb.Message.getFieldWithDefault(msg, 3, ""),
    accountalias: jspb.Message.getFieldWithDefault(msg, 2, ""),
    kind: jspb.Message.getFieldWithDefault(msg, 4, 0),
    resolverattributesMap: (f = msg.getResolverattributesMap()) ? f.toObject(includeInstance, undefined) : [],
    status: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kubeconfig.CredResolverConfig}
 */
proto.kubeconfig.CredResolverConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kubeconfig.CredResolverConfig;
  return proto.kubeconfig.CredResolverConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kubeconfig.CredResolverConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kubeconfig.CredResolverConfig}
 */
proto.kubeconfig.CredResolverConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccountid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setInfravendor(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccountalias(value);
      break;
    case 4:
      var value = /** @type {!proto.kubeconfig.CredentialResolverKind} */ (reader.readEnum());
      msg.setKind(value);
      break;
    case 5:
      var value = msg.getResolverattributesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 6:
      var value = /** @type {!proto.kubeconfig.CredentialResolverStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kubeconfig.CredResolverConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kubeconfig.CredResolverConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kubeconfig.CredResolverConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.CredResolverConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccountid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getInfravendor();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAccountalias();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getKind();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getResolverattributesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(5, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
};


/**
 * optional string AccountId = 1;
 * @return {string}
 */
proto.kubeconfig.CredResolverConfig.prototype.getAccountid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.kubeconfig.CredResolverConfig} returns this
 */
proto.kubeconfig.CredResolverConfig.prototype.setAccountid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string InfraVendor = 3;
 * @return {string}
 */
proto.kubeconfig.CredResolverConfig.prototype.getInfravendor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.kubeconfig.CredResolverConfig} returns this
 */
proto.kubeconfig.CredResolverConfig.prototype.setInfravendor = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string AccountAlias = 2;
 * @return {string}
 */
proto.kubeconfig.CredResolverConfig.prototype.getAccountalias = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.kubeconfig.CredResolverConfig} returns this
 */
proto.kubeconfig.CredResolverConfig.prototype.setAccountalias = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional CredentialResolverKind Kind = 4;
 * @return {!proto.kubeconfig.CredentialResolverKind}
 */
proto.kubeconfig.CredResolverConfig.prototype.getKind = function() {
  return /** @type {!proto.kubeconfig.CredentialResolverKind} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.kubeconfig.CredentialResolverKind} value
 * @return {!proto.kubeconfig.CredResolverConfig} returns this
 */
proto.kubeconfig.CredResolverConfig.prototype.setKind = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * map<string, string> ResolverAttributes = 5;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.kubeconfig.CredResolverConfig.prototype.getResolverattributesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 5, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.kubeconfig.CredResolverConfig} returns this
 */
proto.kubeconfig.CredResolverConfig.prototype.clearResolverattributesMap = function() {
  this.getResolverattributesMap().clear();
  return this;};


/**
 * optional CredentialResolverStatus Status = 6;
 * @return {!proto.kubeconfig.CredentialResolverStatus}
 */
proto.kubeconfig.CredResolverConfig.prototype.getStatus = function() {
  return /** @type {!proto.kubeconfig.CredentialResolverStatus} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.kubeconfig.CredentialResolverStatus} value
 * @return {!proto.kubeconfig.CredResolverConfig} returns this
 */
proto.kubeconfig.CredResolverConfig.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.kubeconfig.CredResolversReq.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kubeconfig.CredResolversReq.prototype.toObject = function(opt_includeInstance) {
  return proto.kubeconfig.CredResolversReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kubeconfig.CredResolversReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.CredResolversReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    configsList: jspb.Message.toObjectList(msg.getConfigsList(),
    proto.kubeconfig.CredResolverConfig.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kubeconfig.CredResolversReq}
 */
proto.kubeconfig.CredResolversReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kubeconfig.CredResolversReq;
  return proto.kubeconfig.CredResolversReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kubeconfig.CredResolversReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kubeconfig.CredResolversReq}
 */
proto.kubeconfig.CredResolversReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.kubeconfig.CredResolverConfig;
      reader.readMessage(value,proto.kubeconfig.CredResolverConfig.deserializeBinaryFromReader);
      msg.addConfigs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kubeconfig.CredResolversReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kubeconfig.CredResolversReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kubeconfig.CredResolversReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.CredResolversReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getConfigsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.kubeconfig.CredResolverConfig.serializeBinaryToWriter
    );
  }
};


/**
 * repeated CredResolverConfig Configs = 1;
 * @return {!Array<!proto.kubeconfig.CredResolverConfig>}
 */
proto.kubeconfig.CredResolversReq.prototype.getConfigsList = function() {
  return /** @type{!Array<!proto.kubeconfig.CredResolverConfig>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.kubeconfig.CredResolverConfig, 1));
};


/**
 * @param {!Array<!proto.kubeconfig.CredResolverConfig>} value
 * @return {!proto.kubeconfig.CredResolversReq} returns this
*/
proto.kubeconfig.CredResolversReq.prototype.setConfigsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.kubeconfig.CredResolverConfig=} opt_value
 * @param {number=} opt_index
 * @return {!proto.kubeconfig.CredResolverConfig}
 */
proto.kubeconfig.CredResolversReq.prototype.addConfigs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.kubeconfig.CredResolverConfig, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.kubeconfig.CredResolversReq} returns this
 */
proto.kubeconfig.CredResolversReq.prototype.clearConfigsList = function() {
  return this.setConfigsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.kubeconfig.GetCredResolversRes.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kubeconfig.GetCredResolversRes.prototype.toObject = function(opt_includeInstance) {
  return proto.kubeconfig.GetCredResolversRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kubeconfig.GetCredResolversRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.GetCredResolversRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    commonres: (f = msg.getCommonres()) && protos_common_pb.CommonRes.toObject(includeInstance, f),
    configsList: jspb.Message.toObjectList(msg.getConfigsList(),
    proto.kubeconfig.CredResolverConfig.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kubeconfig.GetCredResolversRes}
 */
proto.kubeconfig.GetCredResolversRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kubeconfig.GetCredResolversRes;
  return proto.kubeconfig.GetCredResolversRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kubeconfig.GetCredResolversRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kubeconfig.GetCredResolversRes}
 */
proto.kubeconfig.GetCredResolversRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new protos_common_pb.CommonRes;
      reader.readMessage(value,protos_common_pb.CommonRes.deserializeBinaryFromReader);
      msg.setCommonres(value);
      break;
    case 2:
      var value = new proto.kubeconfig.CredResolverConfig;
      reader.readMessage(value,proto.kubeconfig.CredResolverConfig.deserializeBinaryFromReader);
      msg.addConfigs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kubeconfig.GetCredResolversRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kubeconfig.GetCredResolversRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kubeconfig.GetCredResolversRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.GetCredResolversRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommonres();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      protos_common_pb.CommonRes.serializeBinaryToWriter
    );
  }
  f = message.getConfigsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.kubeconfig.CredResolverConfig.serializeBinaryToWriter
    );
  }
};


/**
 * optional CommonRes CommonRes = 1;
 * @return {?proto.kubeconfig.CommonRes}
 */
proto.kubeconfig.GetCredResolversRes.prototype.getCommonres = function() {
  return /** @type{?proto.kubeconfig.CommonRes} */ (
    jspb.Message.getWrapperField(this, protos_common_pb.CommonRes, 1));
};


/**
 * @param {?proto.kubeconfig.CommonRes|undefined} value
 * @return {!proto.kubeconfig.GetCredResolversRes} returns this
*/
proto.kubeconfig.GetCredResolversRes.prototype.setCommonres = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.kubeconfig.GetCredResolversRes} returns this
 */
proto.kubeconfig.GetCredResolversRes.prototype.clearCommonres = function() {
  return this.setCommonres(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kubeconfig.GetCredResolversRes.prototype.hasCommonres = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated CredResolverConfig Configs = 2;
 * @return {!Array<!proto.kubeconfig.CredResolverConfig>}
 */
proto.kubeconfig.GetCredResolversRes.prototype.getConfigsList = function() {
  return /** @type{!Array<!proto.kubeconfig.CredResolverConfig>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.kubeconfig.CredResolverConfig, 2));
};


/**
 * @param {!Array<!proto.kubeconfig.CredResolverConfig>} value
 * @return {!proto.kubeconfig.GetCredResolversRes} returns this
*/
proto.kubeconfig.GetCredResolversRes.prototype.setConfigsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.kubeconfig.CredResolverConfig=} opt_value
 * @param {number=} opt_index
 * @return {!proto.kubeconfig.CredResolverConfig}
 */
proto.kubeconfig.GetCredResolversRes.prototype.addConfigs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.kubeconfig.CredResolverConfig, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.kubeconfig.GetCredResolversRes} returns this
 */
proto.kubeconfig.GetCredResolversRes.prototype.clearConfigsList = function() {
  return this.setConfigsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kubeconfig.DeleteCredResolverReq.prototype.toObject = function(opt_includeInstance) {
  return proto.kubeconfig.DeleteCredResolverReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kubeconfig.DeleteCredResolverReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.DeleteCredResolverReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    accountid: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kubeconfig.DeleteCredResolverReq}
 */
proto.kubeconfig.DeleteCredResolverReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kubeconfig.DeleteCredResolverReq;
  return proto.kubeconfig.DeleteCredResolverReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kubeconfig.DeleteCredResolverReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kubeconfig.DeleteCredResolverReq}
 */
proto.kubeconfig.DeleteCredResolverReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccountid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kubeconfig.DeleteCredResolverReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kubeconfig.DeleteCredResolverReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kubeconfig.DeleteCredResolverReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.DeleteCredResolverReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccountid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string AccountId = 1;
 * @return {string}
 */
proto.kubeconfig.DeleteCredResolverReq.prototype.getAccountid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.kubeconfig.DeleteCredResolverReq} returns this
 */
proto.kubeconfig.DeleteCredResolverReq.prototype.setAccountid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kubeconfig.KubeConfigReq.prototype.toObject = function(opt_includeInstance) {
  return proto.kubeconfig.KubeConfigReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kubeconfig.KubeConfigReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.KubeConfigReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    commonreq: (f = msg.getCommonreq()) && protos_common_pb.CommonReq.toObject(includeInstance, f),
    config: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kubeconfig.KubeConfigReq}
 */
proto.kubeconfig.KubeConfigReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kubeconfig.KubeConfigReq;
  return proto.kubeconfig.KubeConfigReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kubeconfig.KubeConfigReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kubeconfig.KubeConfigReq}
 */
proto.kubeconfig.KubeConfigReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new protos_common_pb.CommonReq;
      reader.readMessage(value,protos_common_pb.CommonReq.deserializeBinaryFromReader);
      msg.setCommonreq(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setConfig(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kubeconfig.KubeConfigReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kubeconfig.KubeConfigReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kubeconfig.KubeConfigReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.KubeConfigReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommonreq();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      protos_common_pb.CommonReq.serializeBinaryToWriter
    );
  }
  f = message.getConfig();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional CommonReq CommonReq = 1;
 * @return {?proto.kubeconfig.CommonReq}
 */
proto.kubeconfig.KubeConfigReq.prototype.getCommonreq = function() {
  return /** @type{?proto.kubeconfig.CommonReq} */ (
    jspb.Message.getWrapperField(this, protos_common_pb.CommonReq, 1));
};


/**
 * @param {?proto.kubeconfig.CommonReq|undefined} value
 * @return {!proto.kubeconfig.KubeConfigReq} returns this
*/
proto.kubeconfig.KubeConfigReq.prototype.setCommonreq = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.kubeconfig.KubeConfigReq} returns this
 */
proto.kubeconfig.KubeConfigReq.prototype.clearCommonreq = function() {
  return this.setCommonreq(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kubeconfig.KubeConfigReq.prototype.hasCommonreq = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string Config = 2;
 * @return {string}
 */
proto.kubeconfig.KubeConfigReq.prototype.getConfig = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.kubeconfig.KubeConfigReq} returns this
 */
proto.kubeconfig.KubeConfigReq.prototype.setConfig = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kubeconfig.KubeConfigRes.prototype.toObject = function(opt_includeInstance) {
  return proto.kubeconfig.KubeConfigRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kubeconfig.KubeConfigRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.KubeConfigRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    commonres: (f = msg.getCommonres()) && protos_common_pb.CommonRes.toObject(includeInstance, f),
    config: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kubeconfig.KubeConfigRes}
 */
proto.kubeconfig.KubeConfigRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kubeconfig.KubeConfigRes;
  return proto.kubeconfig.KubeConfigRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kubeconfig.KubeConfigRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kubeconfig.KubeConfigRes}
 */
proto.kubeconfig.KubeConfigRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new protos_common_pb.CommonRes;
      reader.readMessage(value,protos_common_pb.CommonRes.deserializeBinaryFromReader);
      msg.setCommonres(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setConfig(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kubeconfig.KubeConfigRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kubeconfig.KubeConfigRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kubeconfig.KubeConfigRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.KubeConfigRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommonres();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      protos_common_pb.CommonRes.serializeBinaryToWriter
    );
  }
  f = message.getConfig();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional CommonRes CommonRes = 1;
 * @return {?proto.kubeconfig.CommonRes}
 */
proto.kubeconfig.KubeConfigRes.prototype.getCommonres = function() {
  return /** @type{?proto.kubeconfig.CommonRes} */ (
    jspb.Message.getWrapperField(this, protos_common_pb.CommonRes, 1));
};


/**
 * @param {?proto.kubeconfig.CommonRes|undefined} value
 * @return {!proto.kubeconfig.KubeConfigRes} returns this
*/
proto.kubeconfig.KubeConfigRes.prototype.setCommonres = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.kubeconfig.KubeConfigRes} returns this
 */
proto.kubeconfig.KubeConfigRes.prototype.clearCommonres = function() {
  return this.setCommonres(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kubeconfig.KubeConfigRes.prototype.hasCommonres = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string Config = 2;
 * @return {string}
 */
proto.kubeconfig.KubeConfigRes.prototype.getConfig = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.kubeconfig.KubeConfigRes} returns this
 */
proto.kubeconfig.KubeConfigRes.prototype.setConfig = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kubeconfig.ClusterMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.kubeconfig.ClusterMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kubeconfig.ClusterMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.ClusterMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    clustername: jspb.Message.getFieldWithDefault(msg, 1, ""),
    credresolverid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    clustertagsMap: (f = msg.getClustertagsMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kubeconfig.ClusterMetadata}
 */
proto.kubeconfig.ClusterMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kubeconfig.ClusterMetadata;
  return proto.kubeconfig.ClusterMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kubeconfig.ClusterMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kubeconfig.ClusterMetadata}
 */
proto.kubeconfig.ClusterMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClustername(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCredresolverid(value);
      break;
    case 3:
      var value = msg.getClustertagsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kubeconfig.ClusterMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kubeconfig.ClusterMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kubeconfig.ClusterMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.ClusterMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClustername();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCredresolverid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getClustertagsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string ClusterName = 1;
 * @return {string}
 */
proto.kubeconfig.ClusterMetadata.prototype.getClustername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.kubeconfig.ClusterMetadata} returns this
 */
proto.kubeconfig.ClusterMetadata.prototype.setClustername = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string CredResolverId = 2;
 * @return {string}
 */
proto.kubeconfig.ClusterMetadata.prototype.getCredresolverid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.kubeconfig.ClusterMetadata} returns this
 */
proto.kubeconfig.ClusterMetadata.prototype.setCredresolverid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * map<string, string> ClusterTags = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.kubeconfig.ClusterMetadata.prototype.getClustertagsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.kubeconfig.ClusterMetadata} returns this
 */
proto.kubeconfig.ClusterMetadata.prototype.clearClustertagsMap = function() {
  this.getClustertagsMap().clear();
  return this;};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.kubeconfig.AggregatedClusterMetadata.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kubeconfig.AggregatedClusterMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.kubeconfig.AggregatedClusterMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kubeconfig.AggregatedClusterMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.AggregatedClusterMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    metadata: (f = msg.getMetadata()) && proto.kubeconfig.ClusterMetadata.toObject(includeInstance, f),
    dataresolversList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    status: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kubeconfig.AggregatedClusterMetadata}
 */
proto.kubeconfig.AggregatedClusterMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kubeconfig.AggregatedClusterMetadata;
  return proto.kubeconfig.AggregatedClusterMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kubeconfig.AggregatedClusterMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kubeconfig.AggregatedClusterMetadata}
 */
proto.kubeconfig.AggregatedClusterMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.kubeconfig.ClusterMetadata;
      reader.readMessage(value,proto.kubeconfig.ClusterMetadata.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    case 2:
      var values = /** @type {!Array<!proto.kubeconfig.MetadataResolverType>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addDataresolvers(values[i]);
      }
      break;
    case 3:
      var value = /** @type {!proto.kubeconfig.ClusterInformationStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kubeconfig.AggregatedClusterMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kubeconfig.AggregatedClusterMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kubeconfig.AggregatedClusterMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.AggregatedClusterMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.kubeconfig.ClusterMetadata.serializeBinaryToWriter
    );
  }
  f = message.getDataresolversList();
  if (f.length > 0) {
    writer.writePackedEnum(
      2,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional ClusterMetadata Metadata = 1;
 * @return {?proto.kubeconfig.ClusterMetadata}
 */
proto.kubeconfig.AggregatedClusterMetadata.prototype.getMetadata = function() {
  return /** @type{?proto.kubeconfig.ClusterMetadata} */ (
    jspb.Message.getWrapperField(this, proto.kubeconfig.ClusterMetadata, 1));
};


/**
 * @param {?proto.kubeconfig.ClusterMetadata|undefined} value
 * @return {!proto.kubeconfig.AggregatedClusterMetadata} returns this
*/
proto.kubeconfig.AggregatedClusterMetadata.prototype.setMetadata = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.kubeconfig.AggregatedClusterMetadata} returns this
 */
proto.kubeconfig.AggregatedClusterMetadata.prototype.clearMetadata = function() {
  return this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kubeconfig.AggregatedClusterMetadata.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated MetadataResolverType DataResolvers = 2;
 * @return {!Array<!proto.kubeconfig.MetadataResolverType>}
 */
proto.kubeconfig.AggregatedClusterMetadata.prototype.getDataresolversList = function() {
  return /** @type {!Array<!proto.kubeconfig.MetadataResolverType>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<!proto.kubeconfig.MetadataResolverType>} value
 * @return {!proto.kubeconfig.AggregatedClusterMetadata} returns this
 */
proto.kubeconfig.AggregatedClusterMetadata.prototype.setDataresolversList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!proto.kubeconfig.MetadataResolverType} value
 * @param {number=} opt_index
 * @return {!proto.kubeconfig.AggregatedClusterMetadata} returns this
 */
proto.kubeconfig.AggregatedClusterMetadata.prototype.addDataresolvers = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.kubeconfig.AggregatedClusterMetadata} returns this
 */
proto.kubeconfig.AggregatedClusterMetadata.prototype.clearDataresolversList = function() {
  return this.setDataresolversList([]);
};


/**
 * optional ClusterInformationStatus Status = 3;
 * @return {!proto.kubeconfig.ClusterInformationStatus}
 */
proto.kubeconfig.AggregatedClusterMetadata.prototype.getStatus = function() {
  return /** @type {!proto.kubeconfig.ClusterInformationStatus} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.kubeconfig.ClusterInformationStatus} value
 * @return {!proto.kubeconfig.AggregatedClusterMetadata} returns this
 */
proto.kubeconfig.AggregatedClusterMetadata.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.kubeconfig.GetAvailableClustersRes.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kubeconfig.GetAvailableClustersRes.prototype.toObject = function(opt_includeInstance) {
  return proto.kubeconfig.GetAvailableClustersRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kubeconfig.GetAvailableClustersRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.GetAvailableClustersRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    commonres: (f = msg.getCommonres()) && protos_common_pb.CommonRes.toObject(includeInstance, f),
    clustersList: jspb.Message.toObjectList(msg.getClustersList(),
    proto.kubeconfig.AggregatedClusterMetadata.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kubeconfig.GetAvailableClustersRes}
 */
proto.kubeconfig.GetAvailableClustersRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kubeconfig.GetAvailableClustersRes;
  return proto.kubeconfig.GetAvailableClustersRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kubeconfig.GetAvailableClustersRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kubeconfig.GetAvailableClustersRes}
 */
proto.kubeconfig.GetAvailableClustersRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new protos_common_pb.CommonRes;
      reader.readMessage(value,protos_common_pb.CommonRes.deserializeBinaryFromReader);
      msg.setCommonres(value);
      break;
    case 2:
      var value = new proto.kubeconfig.AggregatedClusterMetadata;
      reader.readMessage(value,proto.kubeconfig.AggregatedClusterMetadata.deserializeBinaryFromReader);
      msg.addClusters(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kubeconfig.GetAvailableClustersRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kubeconfig.GetAvailableClustersRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kubeconfig.GetAvailableClustersRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.GetAvailableClustersRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommonres();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      protos_common_pb.CommonRes.serializeBinaryToWriter
    );
  }
  f = message.getClustersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.kubeconfig.AggregatedClusterMetadata.serializeBinaryToWriter
    );
  }
};


/**
 * optional CommonRes CommonRes = 1;
 * @return {?proto.kubeconfig.CommonRes}
 */
proto.kubeconfig.GetAvailableClustersRes.prototype.getCommonres = function() {
  return /** @type{?proto.kubeconfig.CommonRes} */ (
    jspb.Message.getWrapperField(this, protos_common_pb.CommonRes, 1));
};


/**
 * @param {?proto.kubeconfig.CommonRes|undefined} value
 * @return {!proto.kubeconfig.GetAvailableClustersRes} returns this
*/
proto.kubeconfig.GetAvailableClustersRes.prototype.setCommonres = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.kubeconfig.GetAvailableClustersRes} returns this
 */
proto.kubeconfig.GetAvailableClustersRes.prototype.clearCommonres = function() {
  return this.setCommonres(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kubeconfig.GetAvailableClustersRes.prototype.hasCommonres = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated AggregatedClusterMetadata Clusters = 2;
 * @return {!Array<!proto.kubeconfig.AggregatedClusterMetadata>}
 */
proto.kubeconfig.GetAvailableClustersRes.prototype.getClustersList = function() {
  return /** @type{!Array<!proto.kubeconfig.AggregatedClusterMetadata>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.kubeconfig.AggregatedClusterMetadata, 2));
};


/**
 * @param {!Array<!proto.kubeconfig.AggregatedClusterMetadata>} value
 * @return {!proto.kubeconfig.GetAvailableClustersRes} returns this
*/
proto.kubeconfig.GetAvailableClustersRes.prototype.setClustersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.kubeconfig.AggregatedClusterMetadata=} opt_value
 * @param {number=} opt_index
 * @return {!proto.kubeconfig.AggregatedClusterMetadata}
 */
proto.kubeconfig.GetAvailableClustersRes.prototype.addClusters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.kubeconfig.AggregatedClusterMetadata, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.kubeconfig.GetAvailableClustersRes} returns this
 */
proto.kubeconfig.GetAvailableClustersRes.prototype.clearClustersList = function() {
  return this.setClustersList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.kubeconfig.RegisterClusterReq.prototype.toObject = function(opt_includeInstance) {
  return proto.kubeconfig.RegisterClusterReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.kubeconfig.RegisterClusterReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.RegisterClusterReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    commonreq: (f = msg.getCommonreq()) && protos_common_pb.CommonReq.toObject(includeInstance, f),
    clustername: jspb.Message.getFieldWithDefault(msg, 2, ""),
    accountid: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.kubeconfig.RegisterClusterReq}
 */
proto.kubeconfig.RegisterClusterReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.kubeconfig.RegisterClusterReq;
  return proto.kubeconfig.RegisterClusterReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.kubeconfig.RegisterClusterReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.kubeconfig.RegisterClusterReq}
 */
proto.kubeconfig.RegisterClusterReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new protos_common_pb.CommonReq;
      reader.readMessage(value,protos_common_pb.CommonReq.deserializeBinaryFromReader);
      msg.setCommonreq(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setClustername(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccountid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.kubeconfig.RegisterClusterReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.kubeconfig.RegisterClusterReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.kubeconfig.RegisterClusterReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.kubeconfig.RegisterClusterReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommonreq();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      protos_common_pb.CommonReq.serializeBinaryToWriter
    );
  }
  f = message.getClustername();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAccountid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional CommonReq CommonReq = 1;
 * @return {?proto.kubeconfig.CommonReq}
 */
proto.kubeconfig.RegisterClusterReq.prototype.getCommonreq = function() {
  return /** @type{?proto.kubeconfig.CommonReq} */ (
    jspb.Message.getWrapperField(this, protos_common_pb.CommonReq, 1));
};


/**
 * @param {?proto.kubeconfig.CommonReq|undefined} value
 * @return {!proto.kubeconfig.RegisterClusterReq} returns this
*/
proto.kubeconfig.RegisterClusterReq.prototype.setCommonreq = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.kubeconfig.RegisterClusterReq} returns this
 */
proto.kubeconfig.RegisterClusterReq.prototype.clearCommonreq = function() {
  return this.setCommonreq(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.kubeconfig.RegisterClusterReq.prototype.hasCommonreq = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string ClusterName = 2;
 * @return {string}
 */
proto.kubeconfig.RegisterClusterReq.prototype.getClustername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.kubeconfig.RegisterClusterReq} returns this
 */
proto.kubeconfig.RegisterClusterReq.prototype.setClustername = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string AccountId = 3;
 * @return {string}
 */
proto.kubeconfig.RegisterClusterReq.prototype.getAccountid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.kubeconfig.RegisterClusterReq} returns this
 */
proto.kubeconfig.RegisterClusterReq.prototype.setAccountid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * @enum {number}
 */
proto.kubeconfig.CredentialResolverKind = {
  DEFAULT: 0,
  ENV: 1,
  IMDS: 2,
  PROFILE: 3
};

/**
 * @enum {number}
 */
proto.kubeconfig.CredentialResolverStatus = {
  CRED_RESOLVER_UNKNOWN: 0,
  CRED_REGISTERED_OK: 1,
  CRED_REGISTERED_NOT_OK: 2,
  CRED_SUGGESTION_OK: 101
};

/**
 * @enum {number}
 */
proto.kubeconfig.MetadataResolverType = {
  META_RESOLVER_NOT_SETTED: 0,
  FOX: 2,
  KUBECONFIG: 3,
  CRED_RESOLVER: 4
};

/**
 * @enum {number}
 */
proto.kubeconfig.ClusterInformationStatus = {
  INFO_NOT_SETTED: 0,
  REGISTERED_OK: 1,
  REGISTERED_NOTOK_NO_CRED_RESOLVER: 2,
  REGISTERED_NOTOK_CRED_RES_NOTOK: 3,
  REGISTERED_UNKNOWN: 4,
  SUGGESTION_OK: 101,
  SUGGESTION_NOTOK_NO_CRED_RESOLVER: 102,
  SUGGESTION_NOTOK_CRED_RES_NOTOK: 103
};

goog.object.extend(exports, proto.kubeconfig);
