name: pr-test
on: pull_request
jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"
      - run: |
          set -eux
          echo "machine github.krafton.com login xtrm-cicd-bot password ${{ secrets.GHES_GITHUB_TOKEN }}" >> ~/.netrc
        name: Login  GHES
      - name: Build Backend Single Target
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --clean --snapshot --single-target
          workdir: backend

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          npm install --global pnpm
          pnpm install
        working-directory: electron-app
        name: Init Typescript Env

      - run: |
          make build-frontend
        working-directory: electron-app
        name: Build-Frontend
